// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqedxcsdnaughujteerp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZWR4Y3NkbmF1Z2h1anRlZXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5Mzc3NDcsImV4cCI6MjA3NzUxMzc0N30._uD5jj9nr-ZofiCZlLChsiCQcW7VoBMEkrnFEggEPx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});